"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { animatePageIn, animatePageOut } from "./components/animation";
import { SwitchTransition, Transition } from "react-transition-group";
import { useRouter } from "next/navigation";


const geistMono = Nunito({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const router = useRouter()



  return (
    <html lang="en">
      <body
        className={`w-full flex justify-center items-center bg-neutral-900  antialiased  ${geistMono.variable} `}
      >
        <div className="w-full max-w-[500px] overflow-hidden flex flex-col gap-y-4">
          <Header/>
          
          <section 
          className='w-full md:px-0 px-8  flex overflow-hidden flex-col justify-center items-center'
        id="transition-element">
          
        {children}
        </section>
        <Footer/>
        </div>
      </body>
    </html>
  );
}
